CFLAGS=-g -Wall
TARGETS=test-signal-01-catch test-signal-02-ign test-signal-03-dfl test-signal-04-alarm test-signal-05-sigaction test-signal-06-sigchld

all: $(TARGETS)

clean:  
	rm -f *.o *~ $(TARGETS) core
